import requests
from datetime import datetime
import os

def generate_changelog():
    """
    Generate a detailed changelog from GitHub commits for the Team4-Excelerate-Flutter-Project repository.
    """
    # GitHub API URL for the repository
    repo_url = "https://api.github.com/repos/Armili09/Team4-Excelerate-Flutter-Project/commits"
    
    try:
        print("Fetching commits from GitHub API...")
        commits = []
        page = 1
        
        while True:
            response = requests.get(repo_url, params={'page': page, 'per_page': 100})
            response.raise_for_status()
            data = response.json()
            if not data:
                break  # Exit loop if no more commits
            commits.extend(data)
            page += 1
        
        print(f"Found {len(commits)} commits")
        
        # Generate changelog content
        changelog_content = "# Team 4 Changelog\n\n"
        changelog_content += "This file is automatically generated from GitHub commits.\n\n"
        changelog_content += f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        changelog_content += "---\n\n"
        
        # Group commits by date
        commits_by_date = {}
        
        for commit in commits:
            message = commit['commit']['message']
            date = commit['commit']['committer']['date']
            author = commit['commit']['author']['name']
            sha = commit['sha'][:7]  # Short commit hash
            
            # Parse date to get just the date part
            commit_date = date.split('T')[0]
            
            if commit_date not in commits_by_date:
                commits_by_date[commit_date] = []
            
            commits_by_date[commit_date].append({
                'message': message,
                'author': author,
                'sha': sha,
                'full_date': date
            })
        
        # Write commits grouped by date (newest first)
        for date in sorted(commits_by_date.keys(), reverse=True):
            changelog_content += f"## {date}\n\n"
            
            for commit in commits_by_date[date]:
                # Clean up commit message (remove newlines and extra spaces)
                clean_message = commit['message'].replace('\n', ' ').strip()
                
                changelog_content += f"- **{clean_message}** ({commit['sha']})\n"
                changelog_content += f"  - Author: {commit['author']}\n"
                changelog_content += f"  - Date: {commit['full_date']}\n\n"
        
        # Write to CHANGELOG.md file
        changelog_path = os.path.join(os.path.dirname(__file__), "..", "CHANGELOG.md")
        
        with open(changelog_path, "w", encoding="utf-8") as f:
            f.write(changelog_content)
        
        print(f"Changelog successfully generated at: {changelog_path}")
        print(f"Total commits processed: {len(commits)}")
        
        return True
        
    except requests.exceptions.RequestException as e:
        print(f"Error fetching commits: {e}")
        return False
    except Exception as e:
        print(f"Error generating changelog: {e}")
        return False

if __name__ == "__main__":
    generate_changelog()
